#!/bin/bash
#! This line is a comment
#! Make sure you only have comments and #SBATCH directives between here and the end of the #SBATCH directives, or things will break
#! Name of the job:
#SBATCH -J emu_run
#! Account name for group, use SL2 for paying queue:
#SBATCH -A ACEDO-SL3-CPU
#! Output filename:
#! %A means slurm job ID and %a means array index
#SBATCH --output=%A_%a.out
#! Errors filename:
#SBATCH --error=%A_%a.err

#! Number of nodes to be allocated for the job (for single core jobs always leave this at 1)
#SBATCH --nodes=1

#! Number of tasks. By default SLURM assumes 1 task per node and 1 CPU per task. (for single core jobs always leave this at 1)
#SBATCH --ntasks-per-node=64
#!SBATCH --ntasks=72

#! How many many cores will be allocated per task? (for single core jobs always leave this at 1)
#SBATCH --cpus-per-task=1
#! Estimated runtime: hh:mm:ss (job is force-stopped after if exceeded):
#SBATCH --time=36:00:00
#! Estimated maximum memory needed (job is force-stopped if exceeded):
#! RAM is allocated in ~3380mb blocks, you are charged per block used,
#! and unused fractions of blocks will not be usable by others.
#!SBATCH --mem-per-cpu=3380/6760mb
#SBATCH --mem-per-cpu=3380mb

#! This is the partition name.
#SBATCH -p icelake

#! SBATCH --qos=INTR

#! mail alert at start, end and abortion of execution
#! emails will default to going to your email address
#! you can specify a different email address manually if needed.
#SBATCH --mail-type=ALL

#! Don't put any #SBATCH directives below this line

#! Modify the environment seen by the application. For this example we need the default modules.
. /etc/profile.d/modules.sh                # This line enables the module command
module purge                               # Removes all modules still loaded
module load rhel8/default-icl              # REQUIRED - loads the basic environment
#!module load intel/mkl/2020.4
#!module load intel/bundles/complib/2017.4

#! Insert additional module load commands after this line if needed:
#!module load openmpi/gcc/9.2/4.0.2
#!module load fftw gsl gcc
#!module load miniconda/3 
#!module load libffi-3.2.1-gcc-4.8.5-4s3dshk

echo "Activating environment"

source /home/sp2053/.bashrc

source activate /home/sp2053/.conda/envs/emu_run 

echo "Initializing Python script with ntasks:"
echo $SLURM_NTASKS

mpirun -n $SLURM_NTASKS /home/sp2053/.conda/envs/emulator/bin/python run_mcmc.py

#!srun -n $SLURM_NTASKS --mpi=pmix /home/sp2053/.conda/envs/emulator/bin/python run_mcmc.py

#!python test.py 

#!mpirun /home/sp2053/.conda/envs/21cmfast/bin/python ./test4.py

#!/home/sp2053/.conda/envs/21cmfast/bin/python test4.py 

#!srun -n $SLURM_NTASKS --mpi=pmix /home/sp2053/.conda/envs/jwsthera/bin/python p1_lc_mcmc.py

#!mpiexec -n $SLURM_NTASKS /home/sp2053/.conda/envs/jwsthera/bin/python p1_lc_nest.py
