# general settings
name: Pk_SDC3b_MLP_minmax_extended
num_gpu: auto  # automatic GPU detection
manual_seed: !!int 10

model_type: MLPModel
# network architecture
network_opt:
  hidden_dim: !!int 100
  n_hidden: !!int 6
  out_dim: !!int 1
  activation: ReLU
  out_activation: 


# training settings
train:
  total_iter: !!int 3000
  ema_decay: !!float 0.999
  optimizer_opt:
    type: Adam
    lr: !!float 1e-3
    weight_decay: !!float 1e-4
  scheduler:
    type: MultiStepLR
    milestones: [60000, 90000]
    gamma: !!float 1.0

# dataset options
dataset:
  type: BaseDataset
  batch_size_per_gpu: !!int 20000
  num_worker_per_gpu: !!int 4
  params_opt:
    file: data/SDC3b/parameters_old.npy
    key: parameters
    names: ['zeta_eff', 'zeta_exp', 'rmfp', 'Vc']
    log: []
    discard: []
    normalization: norm_minmax_extended
  targets_opt:
    file: data/SDC3b/power_spectra_old.npy
    offset: !!float 0.0
    log: !!bool false
  data_dims:
    z:
      file: data/SDC3b/z_power_spectra.npy
      log: !!bool false
      lims_nsample: [!!float nan, !!float nan, !!int 20]
    kperp:
      file: data/SDC3b/bins_kper.txt
      log: !!bool true
      lims_nsample: [!!float 5e-2, !!float 5e-1, !!int 20]
    kpar:
      file: data/SDC3b/bins_kpar.txt
      log: !!bool true
      lims_nsample: [!!float 5e-2, !!float 5e-1, !!int 20]

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# validation settings
val:
  val_freq: !!float 256

logger:
  print_freq: !!int 256
  save_checkpoint_freq: !!float 2560
  use_tb_logger: !!bool true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: !!int 29500
