# general settings
name: xHI_SDC3b_minmax
num_gpu: auto  # automatic GPU detection
manual_seed: !!int 10

model_type: MLPModel
# network architecture
network_opt:
  hidden_dim: !!int 100
  n_hidden: !!int 6
  out_dim: !!int 1
  activation: ReLU
  out_activation: ~

# training settings
train:
  total_iter: !!int 10000
  ema_decay: !!float 0.999
  optimizer_opt:
    type: Adam
    lr: !!float 1e-3
    weight_decay: !!float 1e-4
  scheduler:
    type: MultiStepLR
    milestones: [60000, 90000]
    gamma: !!float 1.0

# dataset options
dataset:
  type: BaseDataset
  batch_size_per_gpu: !!int 10000
  num_worker_per_gpu: !!int 4
  params_opt:
    file: data/SDC3b/parameters_old.npy
    key: parameters
    names: ['zeta_eff', 'zeta_exp', 'rmfp', 'Vc']
    log: []
    discard: []
    normalization: norm_standard
  targets_opt:
    file: data/SDC3b/averaged_xHI_old.npy
    offset: !!float 0.0
    log: !!bool false
  data_dims:
    z:
      file: data/SDC3b/z_xHI.npy
      log: !!bool false
      lims_nsample: [!!float 6.1036, !!float 8.726, !!int 2000]

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# validation settings
val:
  val_freq: !!float 1024

logger:
  print_freq: !!int 256
  save_checkpoint_freq: !!float 1280
  use_tb_logger: !!bool true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: !!int 29500
